language: ruby
rvm:
- 2.2
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: GwFoRBTQEhhSNz7bBxVZB3mt8i2IeoGn5wAKvcGLes680AEefL/xXcEidJLRWWy/dkot4OJEYQOtbE42y0Qw/4xtnt6DAbgAtM9j0UWgOguj5JTbNMz6sVRXIAbdEX0Toij6XZUQZaQkcE9nCS7LDz+yq8Z4Ci4AeOOl/h6mwqIvNeFf/ytJFa2ykHvyrhxAo3nStaBYivQwizafbZy37qyjM/8nLdVM9JUZaSu27nAhp0NTTSjmxoe5KfPohI/GK1Yvzd1pcdPv71F+k/jTQv/1r7TXJeJ+D9zucKaQ9j5AfRvPr4QaAokRrk9ddv8846CFVtYW6pvckWQGfFiPJDG6cAtwfva9k0BEoRs20dgHAsFn+GGEUe7VHXeszrJTD199OvgqEnsyfyAtr7kd+UpmtGCHDOtLfzCB6kv8T7T9Mat/aV3vg0rzMHeMXGNiv2YxOMXtn4wxELLAKm46Kyl/F3s2rUZegkyjxMHaK2Xxt+wgrL431Qfm+6V/h4/RtNYNiTvt2osOs6NOf5+p+8B4USahCSRB9Buu2gepoZ2ei7FuDE1j2T4U35I4wq3JjQtoEISPjK7E8JGEOibTeUe27IcO7wMvK6/JaUYOqbTCPVttSXVtxGJ+hk//QFu4zCcn75ckQ77xiOwutluHSdzs1qClFfEVwiZHz78VbhM=
  app: glacial-staging
  on:
    repo: thywen/rails_heroku_test
